# 머신러닝을 위한 기초 수학 살펴보기

출처 : [머신러닝을 위한 기초 수학 살펴보기 // Speaker Deck](https://speakerdeck.com/mingrammer/meosinreoningeul-wihan-gico-suhag-salpyeobogi)

1. 수학의 필요성
2. 선형대수학이란?
3. NumPy로 선형대수학 다뤄보기
4. 추가 기초 수학 살펴보기
5. 선형 회귀 구현해 보기
6. Nex(more LA and Mathmatics)



* 선형대수학
    * 데이터의 표현
    * 계산의 효율
    * 최적화
    * 특성 추출

* 확률과 통계
    * 확률 분포
    * 추론 및 예측
    * 가설 검증
    * 정규화


* 미적분학
    * 해석학적 접근
    * 기울기 계산
    * 편미분
    
    
## 선형대수학

* 벡터 공간, 벡터 연산, 행렬 연산, 차원, 선형 방정식
* 머신러닝, 암호화, 정보 검색, 이미지 프로세싱, 대규모 처리
* 선형대수를 다루기 위해 Numpy를 사용, 순수 파이썬은 좀 느림
* Numpy는 코어가 C/Fortran 기반이라 빠름
* 빠를 뿐만 아니라 배열을 효율적으로 처리해 메모리도 덜 사용 함
* 각종 편리한 고수준 인터페스와 도구들을 제공

### 벡터

* 공간에서의 원소를 표현
* 벡터는 각 원소의 데이터 타입이 동일
* 보통 array로 표현(numpy.array)

In [33]:
import numpy as np

v = np.array([1, 2, 3])
w = np.array([6, -1, 3])

print(v)
print(w)

[1 2 3]
[ 6 -1  3]


In [34]:
v = np.array([1, 2, 3]) # 튜플!! (3)

print(v, v.shape)

[1 2 3] (3,)


In [35]:
w = np.array([[1, 2, 3]]) # 행벡터(1 x 3)

print(w, w.shape)

[[1 2 3]] (1, 3)


In [36]:
u = np.array([[1],[2],[3]]) # 열벡터(3 x 1)

print(u, u.shape)

[[1]
 [2]
 [3]] (3, 1)


### 벡터 연산
벡터는 다음의 연산들을 수행할 수 있음
* 덧셈(addition)
* 뺄셈(subtraction)
* 스칼라곱(Scalar Product)
* 성분곱(Elementwise Multiplication)
* 내적(Inner Product)

In [37]:
v = np.array([1, 3, 5])
w = np.array([2, 4, 6])

In [38]:
print('v + w =', v + w) # 덧셈

v + w = [ 3  7 11]


In [39]:
print('v - w =', v - w) # 뺄셈

v - w = [-1 -1 -1]


In [40]:
print(4 * v) # 곱셈: 스칼라콥

[ 4 12 20]


In [41]:
print(v * w, np.multiply(v, w)) # 곱셈: 성분곱

[ 2 12 30] [ 2 12 30]


In [42]:
print(np.inner(v, w), v.dot(w)) # 내적

44 44


### 행렬 (Matrix)
* m x n 의 형태를 가짐
* 각 행/열을 벡터로 표현 가능
* 보통 2차원 array로 표현

In [30]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(mat)
print(mat.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


#### 행렬 연산
행렬은 다음의 연산들을 수행할 수 있음
* 덧셈(addition)
* 뺄셈(subtraction)
* 스칼라곱(Scalar Product)
* 성분곱(Elementwise Multiplication)
* 행렬곱(Matrix Multiplication)

In [46]:
X = np.array([[3, 4, 2], [1, 3, 7]])
Y = np.array([[1, 0, 1], [2, 1, 1]])

In [48]:
print('X + Y =\n', X + Y, '\n') # 덧셈

X + Y =
 [[4 4 3]
 [3 4 8]] 



In [50]:
print('X - Y =\n', X - Y, '\n') # 뺄셈

X - Y =
 [[ 2  4  1]
 [-1  2  6]] 



In [52]:
print(3 * X) # 곱셈: 스칼라곱

[[ 9 12  6]
 [ 3  9 21]]


In [53]:
print(np.multiply(X, Y)) # 곱셈: 성분곱

[[3 0 2]
 [2 3 7]]


In [55]:
X = np.array([[1, 0, 3], 
              [2, 1, 4]])

Y = np.array([[2, 3], 
              [1, 2], 
              [0, 1]])

# 행렬곱 (2 x 3) 행렬과 x (3 x 2) 행렬을 곱하면 = (2 x 2) 행렬이 나온다.
print(X.dot(Y))

[[ 2  6]
 [ 5 12]]


#### 전치(Transpose)

In [59]:
x = np.array([[3], [4], [5]])
X = np.array([[1, 0, 3], [2, 1, 4]])
# [] 안에 array를 생성하면 [] 안의 데이터가 행이 된다. 

In [57]:
print(x.T)

[[3 4 5]]


In [58]:
print(X.T)

[[1 2]
 [0 1]
 [3 4]]


### 단위 행렬(Identity Matrix)

In [61]:
I = np.identity(6)

print(I)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


### 역행렬(Inverse Matrix)
* 역행렬은 항상 존재하지는 않음

In [65]:
from numpy import linalg

X = np.array([[3, 4], 
              [5, 6]])

Xi = linalg.inv(X)

print(Xi)

print(X.dot(Xi))

[[-3.   2. ]
 [ 2.5 -1.5]]
[[  1.00000000e+00  -8.88178420e-16]
 [  0.00000000e+00   1.00000000e+00]]


### 정규화 
* 전체 sum으로 나눔으로써 [0,1] 구간으로 정규화

In [68]:
x = np.array([10, 3, 41, 12, 9, 1, 3, 34])

y = x / sum(x)

print(y)

[ 0.08849558  0.02654867  0.36283186  0.10619469  0.07964602  0.00884956
  0.02654867  0.30088496]


In [69]:
# 정규분포를 활용해 평균 = 0, 분산 = 1 로 정규화

In [72]:
x = np.array([10, 3, 41, 12, 9, 1, 3, 34])

print(np.mean(x)) # 평균
print(np.std(x)) # 표준편차

y = (x - np.mean(x)) / np.std(x)

y

14.125
14.0751332143


array([-0.29307005, -0.79040104,  1.90939578, -0.15097548, -0.36411734,
       -0.93249561, -0.79040104,  1.41206479])

## 미분 및 그라디언트
![손실 함수 그래프](https://imgur.com/zy2V6LG.png)
이미지 출처 : https://speakerdeck.com/mingrammer/meosinreoningeul-wihan-gico-suhag-salpyeobogi 
* 예측 모델에서의 결과값과 실제 결과값과의 간극의 지표인 차이 "손실"을 줄이기 위함

### 편미분
* 다변수 공간 혹은 함수에서 특정 변수를 대상으로 미분
* 머신러닝에선 보통 행렬을 대상으로 한 행렬 편미분 사용

=> 지금까지 나온 수학개념들로 선형 회귀 모델을 만들어 봄

# 선형 회귀 모델
![선형 회귀 모델](https://imgur.com/DLEvoe1.png)

* 최적의 선형 상관 관계를 표현하는 직선을 찾으려고 함 -> 최적의 베타를 학습

In [92]:
import matplotlib.pyplot as plt
%matplotlib inline

In [101]:
# 데이터의 생성
# data_x = np.linspace(1.0, 10,0, 100)[:, np.newaxis]
# array([], shape=(0, 1), dtype=float64)
data_x = np.random.uniform(low=1.0, high=10.0, size=100)
# data_x
# print(data_x)
# data_y = np.sin(data_x) + 0.1 * np.power(data_x, 2) + 0.5 * np.random.randn

# data_x /= np.max(data_x)