출처 : [numpy_exercises/Array_creation_routines_solution.ipynb at master · Kyubyong/numpy_exercises](https://github.com/Kyubyong/numpy_exercises/blob/master/Array_creation_routines_solution.ipynb)

# 배열 생성 루틴
## 1과 0

In [1]:
import numpy as np

초기화 하지 않아도 되는 2*2 정수형 배열을 생성한다. 

In [2]:
np.empty([2, 2], int)

array([[                  0,                   0],
       [1185291126929227789,  865276073003188224]])

X = np.array([1,2,3], [4,5,6], np.int32) 이와 같은 shape와 type으로 X를 만든다.

In [3]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[          0,           0,   272860336],
       [-2147483648,           2,           0]], dtype=int32)

대각선을 1로 만들고 나머지에 0을 채워 3차원 배열을 만든다.

In [4]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

1로 채워지는 3*2 의 float 형태의 숫자 배열을 만든다.

np.ones 를 사용하면 안의 숫자가 1로 채워진다.

In [6]:
np.ones([3,2], float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

x = np.arange(4, dtype=np.int64) 같은 shape와 type의 X 배열을 만든다.

In [7]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1])

0으로 채워진 3*2 float 형태의 배열을 만든다.

np.zeros 로 배열을 만들면 내부가 0으로 채워진다.

In [8]:
np.zeros((3,2), float)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

x = np.arange(4, dtype=np.int64) x와 같은 shape와 type을 갖는 0의 배열을 만듭니다.

np.zeros_like 를 사용하면 0으로된 배열이 생긴다.


In [9]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0])

6으로 채워진 2*5의 배열을 만든다.

In [10]:
np.full((2,5), 6, dtype=np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

In [11]:
# 1로 채워진 배열을 만들고 6을 곱해 주어도 된다.
np.ones([2, 5], dtype=np.uint) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

x = np.arange(4, dtype=np.int64) 6으로 채워진 x와 같은 shape와 type의 배열을 생성한다.

In [12]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6])

In [13]:
np.ones_like(x) * 6

array([6, 6, 6, 6])

## 기존 데이터 활용
[1, 2, 3]을 갖는 배열을 생성한다.

In [14]:
np.array([1,2,3])

array([1, 2, 3])

x = [1,2] 를 배열로 변환한다.

In [15]:
x = [1, 2]
np.asarray(x)

array([1, 2])

X = np.array([[1,2], [3,4]]) 를 행렬로 변환한다.

In [16]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

x = [1, 2] 를 float 배열로 변환한다.

np.asfarray를 사용하거나 asarray에 float을 지정해 준다.

In [17]:
x = [1, 2]
np.asfarray(x)

array([ 1.,  2.])

In [18]:
np.asarray(x, float)

array([ 1.,  2.])

x = np.array([30])를 30과 같은 단일 요소의 스칼라로 변환한다.

In [19]:
x = np.array([30])
np.asscalar(x)

30

In [20]:
x[0]

30

x = np.array([1, 2, 3]) x와는 다른 id를 갖는 배열 x의 사본을 만든다.

In [21]:
x = np.array([1, 2, 3])
y = np.copy(x)

print(id(x), x)
print(id(y), y)

4404152880 [1 2 3]
4404162928 [1 2 3]


## 수치 범위
2, 4, 6, 8, ....,100 짝수로 구성된 배열을 생성한다.

In [22]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

3과 10 사이에 50개의 균일하게 간격을 둔 요소의 1차원 배열을 만든다.

In [23]:
np.linspace(3., 10, 50)

array([  3.        ,   3.14285714,   3.28571429,   3.42857143,
         3.57142857,   3.71428571,   3.85714286,   4.        ,
         4.14285714,   4.28571429,   4.42857143,   4.57142857,
         4.71428571,   4.85714286,   5.        ,   5.14285714,
         5.28571429,   5.42857143,   5.57142857,   5.71428571,
         5.85714286,   6.        ,   6.14285714,   6.28571429,
         6.42857143,   6.57142857,   6.71428571,   6.85714286,
         7.        ,   7.14285714,   7.28571429,   7.42857143,
         7.57142857,   7.71428571,   7.85714286,   8.        ,
         8.14285714,   8.28571429,   8.42857143,   8.57142857,
         8.71428571,   8.85714286,   9.        ,   9.14285714,
         9.28571429,   9.42857143,   9.57142857,   9.71428571,
         9.85714286,  10.        ])

3과 10 사이의 로그 눈금에 균등하게 간격을 둔 50 요소의 1차원 배열을 만든다.

In [24]:
np.logspace(3., 10., 50, endpoint=False)

array([  1.00000000e+03,   1.38038426e+03,   1.90546072e+03,
         2.63026799e+03,   3.63078055e+03,   5.01187234e+03,
         6.91830971e+03,   9.54992586e+03,   1.31825674e+04,
         1.81970086e+04,   2.51188643e+04,   3.46736850e+04,
         4.78630092e+04,   6.60693448e+04,   9.12010839e+04,
         1.25892541e+05,   1.73780083e+05,   2.39883292e+05,
         3.31131121e+05,   4.57088190e+05,   6.30957344e+05,
         8.70963590e+05,   1.20226443e+06,   1.65958691e+06,
         2.29086765e+06,   3.16227766e+06,   4.36515832e+06,
         6.02559586e+06,   8.31763771e+06,   1.14815362e+07,
         1.58489319e+07,   2.18776162e+07,   3.01995172e+07,
         4.16869383e+07,   5.75439937e+07,   7.94328235e+07,
         1.09647820e+08,   1.51356125e+08,   2.08929613e+08,
         2.88403150e+08,   3.98107171e+08,   5.49540874e+08,
         7.58577575e+08,   1.04712855e+09,   1.44543977e+09,
         1.99526231e+09,   2.75422870e+09,   3.80189396e+09,
         5.24807460e+09,

##  행렬 구성

X = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
X의 대각선 [0, 5, 10] 을 구한다.

In [25]:
X = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [26]:
X.diagonal()

array([ 0,  5, 10])

대각선이 [1, 2, 3, 4]로 구성되고 나머지가 0으로 채워진 2차원 배열을 만든다.

In [27]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])


3*5 배열에, 첫줄은 2번째 줄부터 1이 하나 씩 늘어나는 행렬을 만든다.

array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])

In [28]:
np.tri(3, 5, -1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

다음과 같이 대각선을 포함한 오른쪽 위의 숫자가 0으로 채워지는 행렬을 만든다.

array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])

In [29]:
np.tril(np.arange(1, 13).reshape(4,3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

위와 반대로 대각선 아래의 숫자가 0으로 채워지는 배열을 만든다.

array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])

In [30]:
np.triu(np.arange(1, 13).reshape(4,3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])