출처 : [numpy_exercises/Array_manipulation_routines_Solutions.ipynb at master · Kyubyong/numpy_exercises](https://github.com/Kyubyong/numpy_exercises/blob/master/Array_manipulation_routines_Solutions.ipynb)
# 배열 조작 루틴

In [1]:
import numpy as np
np.__version__

'1.13.3'

## Q1. 
x를 모든 원소가 1로 채워진 ndarray[10, 10, 3] 라고 하자. 두번째 차원의 크기가 동일하게 150이 되도록 변경한다.

In [2]:
x = np.ones([10, 10, 3])
out1 = np.reshape(x, [-1, 150])
out2 = np.ones([10, 10, 3]).reshape([-1, 150])
print(out1)
assert np.allclose(out1, out2)
out1.shape

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  

(2, 150)

## Q2.
배열 [[1, 2, 3], [4, 5, 6]] 을 [1 4 2 5 3 6] 으로 변환한다.

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = np.ravel(x, order='F')
out2 = x.flatten(order='F')

assert np.allclose(out1, out2)
print(out1)
print(out2)

[1 4 2 5 3 6]
[1 4 2 5 3 6]


## Q3.
[[1, 2, 3], [4, 5, 6]]에서 5번째 원소를 찾는다.

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = x.flat[4]
out2 = np.ravel(x)[4]

assert np.allclose(out1, out2)
print(out1)
print(out2)

5
5


## Q4. 
x를 3차원 배열(3, 4, 5)라고 하자, (4, 3, 5)가 되도록 x의 차원을 고정한다.

In [5]:
x = np.zeros((3, 4, 5))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose([1, 0, 2])
assert out1.shape == out2.shape
out1.shape

(4, 3, 5)

## Q5. 
x를 임의의 2차원 배열 (3, 4)의 형태를 갖는다고 하자. (4, 3)이 되도록 변경한다. 

In [6]:
x = np.zeros((3, 4))
print(x)
out1 = np.swapaxes(x, 1, 0)
print(out1)
out2 = x.transpose()
print(out2)
out3 = x.T
print(out3)
assert out1.shape == out2.shape == out3.shape
out1.shape

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


(4, 3)

## Q5.
x를 임의의 2 차원 배열 형태 (3, 4)라고하자. 새 모양이 (3, 1, 4)가 될 수 있도록 nex 축을 추가한다.

In [7]:
x = np.zeros((3, 4))
np.expand_dims(x, axis=1).shape

(3, 1, 4)

## Q6. 
x를 shape (3, 4, 1)의 임의의 3차원 배열이라고하자. shape가 (3, 4)가되도록 1 차원 항목을 제거한다.

In [8]:
x = np.zeros((3, 4, 1))
np.squeeze(x).shape

(3, 4)

## Q7. 
x를 
[[1 2 3] 
[4 5 6]]
의 배열이라고 하자. 

그리고 y를 [[7 8 9] [10 11 12]]라 한다. 

그리고 x와 y를 다음과 같이 보이도록 만든다.

[[1, 2, 3, 7, 8, 9], 
[4, 5, 6, 10, 11, 12]].

np.concatenate((x, y),1)와 np.hstack 으로 두 개의 배열을 합칠 수 있다.

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

out1 = np.concatenate((x, y),1)
print(out1)
out2 = np.hstack((x, y))
print(out2)
assert np.allclose(out1, out2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Q8. 
x를 [[1 2 3] [4 5 6]]의 배열이라고 하자.
그리고 y를 [[7 8 9] [10 11 12]]라 한다.
그리고 x와 y를 다음과 같이 보이도록 만든다.

[[ 1 2 3] <br/>
[ 4 5 6]<br/>
[ 7 8 9]<br/>
[10 11 12]]<br/>


np.concatenate 에 0옵션을 주면 세로로 배열을 합쳐준다.
np.vstack 을 사용해도 세로로 배열을 합쳐준다.

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 0)
print(out1)
out2 = np.vstack((x, y))
print(out2)
assert np.allclose(out1, out2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Q8.
배열 x [1 2 3], y [4 5 6] 가 있다.

[[1 4]<br/>
 [2 5]<br/>
 [3 6]]<br/>
 로 변환한다.

In [11]:
x = np.array((1, 2, 3))
y = np.array((4, 5, 6))

out1 = np.column_stack((x, y))
print(out1)
out2 = np.dstack((x, y))
print(out2)
out3 = np.vstack((x, y)).T
print(out3)

assert np.allclose(out1, out2)
assert np.allclose(out2, out3)

[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[[1 4]
 [2 5]
 [3 6]]


## Q9. 
배열 x  [[1], [2], [3]], y [[4], [5], [6]]이 있다.

[[[1, 4]], [[2, 5]], [[3, 6]]] 으로 변환한다.

In [12]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
out = np.dstack((x, y))
out

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

## Q10. 
배열 x [1, 2, 3, ..., 9] 가 있다. 
x를 3개의 배열로 나눈다. 그리고 각 배열은 원래 순서대로 4, 2, 3개의 원소를 갖도록 한다.

In [13]:
# 1부터 9까지 있는 배열을 만든다.
x = np.arange(1, 10)
# 4번째, 6번째에서 나눈다.
np.split(x, [4, 6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

## Q11. 
배열 x 

[[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.]],
[[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]]] 가 있다.

다음과 같이 보이도록 2개로 나눈다.

[[[ 0., 1., 2.],
[ 4., 5., 6.]],


[[ 8., 9., 10.],
[ 12., 13., 14.]]]

그리고 나머지를 다음과 같이 나눈다.

[[[ 3.],
[ 7.]],
[[ 11.],
[ 15.]]].

In [14]:
# 0에서 15까지 있는 배열을 만들고 원소가 4개인 배열 2개씩 만든다.
x = np.arange(16).reshape(2, 2, 4)
print(x)
# 왼쪽부터 원소 3개를 갖도록 나눈다.
out1 = np.split(x, [3], axis=2)
print(out1)
out2 = np.dsplit(x, [3])
print(out2)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]
[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


## Q12.
다음과 같은 배열 x가 있다.

[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],

[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]].

두 번째 축을 따라 2개의 배열로 나눈다.

In [15]:
x = np.arange(16).reshape((4, 4))
print(x)
out1 = np.hsplit(x, 2)
print(out1)
out2 = np.split(x, 2, 1)
print(out2)

assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## Q13.
다음과 같은 배열 x가 있다.

[[ 0., 1., 2., 3.],<br/>
[ 4., 5., 6., 7.],<br/>
[ 8., 9., 10., 11.],<br/>
[ 12., 13., 14., 15.]].<br/>

첫번째 축을 따라 2개의 배열로 나눈다.

In [16]:
x = np.arange(16).reshape((4, 4))
print(x)
out1 = np.vsplit(x, 2)
print(out1)
out2 = np.split(x, 2, 0)
print(out2)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## Q14.
배열 x [0, 1, 2]가 있다. 다음과 같이 변환한다.

[[0, 1, 2, 0, 1, 2],
[0, 1, 2, 0, 1, 2]].

In [17]:
x = np.array([0, 1, 2])
out1 = np.tile(x, [2, 2])
print(out1)
out2 = np.resize(x, [2, 6])
print(out2)
assert np.allclose(out1, out2)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


## Q15.
배열 x [0, 1, 2]가 있다. [0, 0, 1, 1, 2, 2] 로 변환한다.

In [18]:
x = np.array([0, 1, 2])
# 지정해준 숫자만큼 원소를 반복한다.
np.repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

## Q16.
다음과 같은 배열 x가 있다.  [0, 0, 0, 1, 2, 3, 0, 2, 1, 0]
앞뒤에 있는 0을 제거한다.

In [19]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
out = np.trim_zeros(x)
out

array([1, 2, 3, 0, 2, 1])

## Q17.
배열 x [2, 2, 1, 5, 4, 5, 1, 2, 3] 가 있다.

이 배열의 고유한 원소와 그 갯수가 있는 두 배열을 만든다.

In [20]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
u, indices = np.unique(x, return_counts=True)
print(u, indices)

[1 2 3 4 5] [2 3 1 1 2]


## Q18.
다음과 같은 배열 x가 있다.
[[ 1 2]
[ 3 4]

2번째 축을 기준으로 x를 뒤집는다.

In [21]:
x = np.array([[1, 2], [3, 4]])
out1 = np.fliplr(x)
print(out1)
out2 = x[:, ::-1]
print(out2)
assert np.allclose(out1, out2)

[[2 1]
 [4 3]]
[[2 1]
 [4 3]]


## Q19.
다음과 같은 배열 x가 있다.
[[ 1 2]
[ 3 4]
첫번째 축을 기준으로 x를 뒤집는다.

In [22]:
x = np.array([[1, 2], [3, 4]])
out1 = np.flipud(x)
print(out1)
out2 = x[::-1, :]
print(out2)
assert np.allclose(out1, out2)

[[3 4]
 [1 2]]
[[3 4]
 [1 2]]


## Q20. 
다음과 같은 배열 x가 있다.
[[ 1 2]
[ 3 4]
반시계 방향으로 90도 회전한다.

In [23]:
x = np.array([[1, 2], [3, 4]])
out = np.rot90(x)
print(out)

[[2 4]
 [1 3]]


## Q21.
다음과 같은 배열 x가 있다. 

[[ 1 2 3 4]
[ 5 6 7 8].

2번째 축을 기준으로 오른쪽으로 한칸씩 이동한다.

In [24]:
x = np.arange(1, 9).reshape([2, 4])
np.roll(x, 1, axis=1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])