출처 : http://chris-chris.ai/2017/11/26/conv-in-numpy/ 따라쓰기

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import dtypes

## 1. Setting up the initial values

In [2]:
# 1. Setting up initial values

x = np.zeros((7, 7, 3))
x[:, :, 0] = np.mat(
    "0 0 0 0 0 0 0;0 0 1 0 1 0 0;0 2 1 0 1 2 0;0 0 2 0 0 1 0;0 2 0 1 0 0 0;0 0 0 1 2 2 0;0 0 0 0 0 0 0"
).A
x[:, :, 1] = np.mat(
    "0 0 0 0 0 0 0;0 1 0 0 1 1 0;0 0 2 2 1 1 0;0 2 1 2 1 0 0;0 2 1 1 2 2 0;0 1 2 0 2 2 0;0 0 0 0 0 0 0"
).A
x[:, :, 2] = np.mat(
    "0 0 0 0 0 0 0;0 2 1 1 1 1 0;0 2 2 1 2 1 0;0 1 1 0 2 2 0;0 2 1 2 2 0 0;0 1 2 2 0 0 0;0 0 0 0 0 0 0"
).A
x

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  1.,  2.],
        [ 1.,  0.,  1.],
        [ 0.,  0.,  1.],
        [ 1.,  1.,  1.],
        [ 0.,  1.,  1.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 2.,  0.,  2.],
        [ 1.,  2.,  2.],
        [ 0.,  2.,  1.],
        [ 1.,  1.,  2.],
        [ 2.,  1.,  1.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  2.,  1.],
        [ 2.,  1.,  1.],
        [ 0.,  2.,  0.],
        [ 0.,  1.,  2.],
        [ 1.,  0.,  2.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 2.,  2.,  2.],
        [ 0.,  1.,  1.],
        [ 1.,  1.,  2.],
        [ 0.,  2.,  2.],
        [ 0.,  2.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  2.,  2.],
        [ 1.,  0.,  2.],
        [ 2.,  

In [3]:
x = np.reshape(x, (1, 7, 7, 3))
print("x:",x)

x: [[[[ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 0.  1.  2.]
   [ 1.  0.  1.]
   [ 0.  0.  1.]
   [ 1.  1.  1.]
   [ 0.  1.  1.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 2.  0.  2.]
   [ 1.  2.  2.]
   [ 0.  2.  1.]
   [ 1.  1.  2.]
   [ 2.  1.  1.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 0.  2.  1.]
   [ 2.  1.  1.]
   [ 0.  2.  0.]
   [ 0.  1.  2.]
   [ 1.  0.  2.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 2.  2.  2.]
   [ 0.  1.  1.]
   [ 1.  1.  2.]
   [ 0.  2.  2.]
   [ 0.  2.  0.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 0.  1.  1.]
   [ 0.  2.  2.]
   [ 1.  0.  2.]
   [ 2.  2.  0.]
   [ 2.  2.  0.]
   [ 0.  0.  0.]]

  [[ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]
   [ 0.  0.  0.]]]]


In [4]:
w = np.zeros((3, 3, 3, 2))

w[:, :, 0, 0] = np.mat("0 0 1;-1 1 1;0 1 0").A
w[:, :, 1, 0] = np.mat("1 1 1;0 1 1;0 1 0").A
w[:, :, 2, 0] = np.mat("-1 0 0;-1 1 1;0 -1 0").A
w

array([[[[ 0.,  0.],
         [ 1.,  0.],
         [-1.,  0.]],

        [[ 0.,  0.],
         [ 1.,  0.],
         [ 0.,  0.]],

        [[ 1.,  0.],
         [ 1.,  0.],
         [ 0.,  0.]]],


       [[[-1.,  0.],
         [ 0.,  0.],
         [-1.,  0.]],

        [[ 1.,  0.],
         [ 1.,  0.],
         [ 1.,  0.]],

        [[ 1.,  0.],
         [ 1.,  0.],
         [ 1.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 1.,  0.],
         [ 1.,  0.],
         [-1.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]]])

In [5]:
# w1 = np.zeros((3,3,3))
w[:, :, 0, 1] = np.mat("0 0 0;1 1 -1;-1 1 1").A
w[:, :, 1, 1] = np.mat("0 1 -1;1 1 -1;-1 1 -1").A
w[:, :, 2, 1] = np.mat("1 1 0;-1 -1 0;0 -1 1").A
w

array([[[[ 0.,  0.],
         [ 1.,  0.],
         [-1.,  1.]],

        [[ 0.,  0.],
         [ 1.,  1.],
         [ 0.,  1.]],

        [[ 1.,  0.],
         [ 1., -1.],
         [ 0.,  0.]]],


       [[[-1.,  1.],
         [ 0.,  1.],
         [-1., -1.]],

        [[ 1.,  1.],
         [ 1.,  1.],
         [ 1., -1.]],

        [[ 1., -1.],
         [ 1., -1.],
         [ 1.,  0.]]],


       [[[ 0., -1.],
         [ 0., -1.],
         [ 0.,  0.]],

        [[ 1.,  1.],
         [ 1.,  1.],
         [-1., -1.]],

        [[ 0.,  1.],
         [ 0., -1.],
         [ 0.,  1.]]]])

In [6]:
stride = 2
scope = "conv_in_numpy"
act = tf.nn.relu  # activation
pad = 'VALID'  # padding
nf = 2  # number of filters
rf = 3  # filter size
b = [1, 0]  # bias

In [7]:
np_o = np.zeros((1, 3, 3, 2))
s = stride

## 2. Convolution in Tensorflow

In [8]:
print("--- Convolution in Tensorflow ---")

tf_x = tf.constant(x, dtype=dtypes.float32)

with tf.Session() as sess:
    with tf.variable_scope(scope):
        nin = tf_x.get_shape()[3].value
        tf_w = tf.get_variable("w", [rf, rf, nin, nf], initializer=tf.constant_initializer(w))
        tf_b = tf.get_variable(
            "b", [nf],
            initializer=tf.constant_initializer(b, dtype=dtypes.float32))
        tf_z = tf.nn.conv2d(
            tf_x, w, strides=[1, stride, stride, 1], padding=pad) + b
        tf_h = act(tf_z)
        sess.run(tf.global_variables_initializer())
        tf_o = sess.run(tf_z)
        print("tf_o0:\n", tf_o[0, :, :, 0])
        print("tf_o1:\n", tf_o[0, :, :, 1])

--- Convolution in Tensorflow ---
tf_o0:
 [[  6.   4.   3.]
 [ 13.   7.   4.]
 [ 10.   9.   5.]]
tf_o1:
 [[ -1.  -3.   1.]
 [  0.   6.   2.]
 [  1.  -3.  12.]]


In [10]:
# np.testing.assert_almost_equal(tf_o, np_o)

* CNN Animation, Andrej Karpathy, Stanford CS231n lecture : https://cs231n.github.io/convolutional-networks/