# 입력과 출력 Input and Output

In [1]:
from __future__ import print_function
import numpy as np
np.__version__

'1.13.3'

In [2]:
from datetime import date
date.today()

datetime.date(2017, 11, 6)

## Numpy binary files (NPY, NPZ)
## Q1.
x를 temp.npy에 저장하고 로드한다.<br/>
Save x into temp.npy and load it.

In [3]:
x = np.arange(10)
print(x)
np.save('temp.npy', x)

# temp.npy가 있는지 체크한다.
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.npy')
    print(x2)
    print(np.array_equal(x, x2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
True


## Q2.
x 와 y를 하나의 파일 'temp.npz'에 저장하고 로드한다.<br/>
Save x and y into a single file 'temp.npz' and load it.

In [4]:
x = np.arange(10)
y = np.arange(11, 20)
print(x, y)
np.savez('temp.npz', x=x, y=y)
# 압축해서 저장하길 원한다면, savez_compressed를 사용한다.
# np.savez_compressed('temp.npz', x=x, y=y) 
with np.load('temp.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(np.array_equal(x, x2))
    print(np.array_equal(y, y2))

[0 1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19]
True
True


## Text files
## Q3.
x 를 'temp.txt'에 문자열 형태로 저장하고 로드한다.<br/>
Save x to 'temp.txt' in string format and load it.

In [5]:
# 0부터 9까지 있는 2행 5열의 행렬을 만든다.
x = np.arange(10).reshape(2, 5)
print(x)
header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt', x, fmt='%d', header=header)
np.loadtxt('temp.txt')

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

## Q4.
x, y, z를 'temp.txt'에 문자열로 저장하고 줄단위로 로드한다.<br/>
Save x, y, and z to 'temp.txt' in string format line by line, then load it.

In [6]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)
print(x, y, z)
np.savetxt('temp.txt', (x, y, z), fmt='%d')
np.loadtxt('temp.txt')

[0 1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19 20] [22 23 24 25 26 27 28 29 30 31]


array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.]])

## Q5.
x를 바이트로 변환하고 배열로 로드한다.<br/>
Convert x into bytes, and load it as array.

In [7]:
x = np.array([1, 2, 3, 4])
print(x)
# 함수명은 tostring이지만 실제로는 바이트를 반환한다.
x_bytes = x.tostring()
print(x_bytes)
# x 가 not이면 1차원 배열을 반환한다.
x2 = np.fromstring(x_bytes, dtype=x.dtype)
print(x2)
print(np.array_equal(x, x2))

[1 2 3 4]
b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'
[1 2 3 4]
True


## Q6.
a를 ndarray로 변환하고 다시 리스트로 변환한다.<br/>
문제는 ndarray로 변환하는 것인데, 솔루션에는 array로 변환한다.
ndarray로 변환을 하게 되면 다음과 같은 타입에러가 난다.

```
x = np.ndarray(a)
TypeError: 'list' object cannot be interpreted as an integer
```


여기에서 ndarray를 다시 알아보면, ndarray는 N차원의 배열 객체다.
ndarray는 기존 파이썬과는 다르게 오직 같은 종류의 데이터만을 배열에 담을 수 있다.


np.ndarray를 사용하라는 것으로 문제를 이해했는데 그냥 n차원의 배열을 얘기할때도 ndarray를 사용하는 것 같다.


Convert a into an ndarray and then convert it into a list again.

In [8]:
a = [[1, 2], [3, 4]]
x = np.array(a)
print(a)
a2 = x.tolist()
print(a2)
print(a == a2)

[[1, 2], [3, 4]]
[[1, 2], [3, 4]]
True


# String formatting
## Q7.
x 를 문자열로 변환하고 revert 한다.<br/>
Convert x to a string, and revert it.

In [9]:
# 0~9까지 있는 2행 5열의 배열을 만든다.
x = np.arange(10).reshape(2, 5)
x_str = np.array_str(x)
print(x_str, "\n", type(x_str))
x_str = x_str.replace("[", "")
x_str = x_str.replace("]", "")
x2 = np.fromstring(x_str, dtype=x.dtype, sep=" ").reshape(x.shape)
assert np.array_equal(x, x2)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 <class 'str'>


## Text formatting options
## Q8.
x를 프린트 하고 모든 원소가 precision=1, no suppress 로 표시되도록 한다.<br/>
Print x such that all elements are displayed with precision=1, no suppress.

In [10]:
x = np.random.uniform(size=[10,100])
np.set_printoptions(precision=1, threshold=np.nan, suppress=True)
print(x)

[[ 0.3  0.7  0.9  0.7  0.5  0.1  0.2  0.3  0.8  0.4  0.1  0.3  0.7  0.8
   0.3  0.7  0.9  0.4  0.6  0.4  0.4  0.1  0.1  0.9  0.7  0.5  0.6  0.6
   0.1  0.2  0.5  0.4  0.1  0.7  0.5  0.9  0.2  0.9  0.7  0.7  0.9  1.   0.4
   0.3  1.   0.4  0.8  0.8  0.   0.   0.   0.3  0.9  0.5  0.5  0.7  0.1
   0.4  0.6  0.1  0.7  0.1  0.3  0.6  0.6  0.9  0.5  0.6  0.1  0.1  0.8  1.
   0.5  0.5  0.2  0.4  0.7  0.4  0.7  0.   0.1  0.5  0.3  0.4  0.   0.2
   0.4  0.5  0.7  0.8  0.5  0.4  0.6  0.7  0.2  0.6  0.9  0.2  0.3  0.6]
 [ 0.9  0.8  0.7  1.   0.1  0.6  0.4  0.   0.4  0.5  0.7  0.8  0.5  0.3
   0.1  0.3  0.5  0.9  0.4  0.5  0.9  0.6  0.1  0.   0.7  0.2  0.6  0.1
   0.3  0.9  0.   0.5  0.   0.5  0.6  0.4  0.9  0.6  0.9  0.2  0.4  0.9
   0.8  0.9  0.   0.8  0.4  0.6  0.5  0.9  0.5  0.4  0.7  0.5  0.3  0.   0.6
   0.9  0.9  0.5  0.4  0.9  0.5  0.3  0.9  0.7  0.7  0.4  0.7  0.2  1.   0.2
   0.5  0.5  0.3  0.2  1.   0.4  0.1  0.2  0.   0.3  1.   1.   0.   0.5
   0.5  0.1  0.4  0.5  0.9  0.2  0.2  0.6  0

## Base-n representations
## Q9.
12를 문자열 형식의 2진수로 변환한다.<br/>
Convert 12 into a binary number in string format.

In [11]:
out1 = np.binary_repr(12)
out2 = np.base_repr(12, base=2)
assert out1 == out2
print(out1)

1100


## Q10.
12를 문자열 형식의 16진수로 변환한다. <br/>
솔루션에는 12의 이진수인 1100을 넣었는데 12로 넣는게 맞지 않을까 싶음<br/>
Convert 12 into a hexadecimal number in string format.

In [12]:
out1 = np.base_repr(1100, base=16)
out2 = np.base_repr(12, base=16)
print(out1, out2)

44C C
