# 선형대수 Linear algebra


In [1]:
!python3 --version

Python 3.6.1


In [2]:
import numpy as np
np.__version__

'1.13.3'

## 행렬 벡터 연산 Matrix and vector product
## Q1.
다음 코드의 결과를 예측한다.<br/>
Predict the results of the following code.<br/>
(matmul은 matrix multiply로 이해한다.)

In [3]:
x = [1, 2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y))
print(np.inner(y,x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


## Q2. 
다음 코드의 결과를 예측한다.<br/>
Predict the results of the following code.

In [4]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


## Q3.
다음 코드의 결과를 예측한다.<br/>
Predict the results of the following code.

In [5]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


### 벡터 연산
벡터는 다음의 연산들을 수행할 수 있음
* 덧셈(addition)
* 뺄셈(subtraction)
* 스칼라곱(Scalar Product)
* 성분곱(Elementwise Multiplication)
* 내적(Inner Product)


## Q4.
다음 코드의 결과를 예측한다.<br/>
Predict the results of the following code.

In [6]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decomposition
## Q5.
x의 숄레스키 분해에서 하위 삼각형 L을 구해서 검증한다.<br/>
Get the lower-trianglular L in the Cholesky decomposition of x and verify it.

* 숄레스키 분해란?
    * [A][x] = [b] 에서 행렬 A가 대칭행렬일 때의 풀이법을 숄레스키 분해라 함
    * 대칭행렬(symmetric matrix)은 행렬의 요소와 모든 i, j에 대해 n차 정사각행렬 A가 있다면, 대각요소를 중심으로 행렬 A와 그 전치행렬이 같을 때 인 행렬을 대칭행렬이라 한다.
    * 숄레스키 분해(Cholesky decomposition)는 에르미트 행렬(Hermitian matrix), 양의 정부호행렬(positive-definite matrix)의 분해에서 사용된다. 촐레스키 분해의 결과는 하삼각행렬과 하삼각행렬의 켤레전치 행렬의 곱으로 표현된다.
    * 선형 방정식 시스템을 푸는 실제 응용에서, 촐레스키 분해가 LU 분해와 비교했을 때 약 두 배 정도 효율적인 것으로 알려졌다.

* [숄레스키 분해 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%88%84%EB%A0%88%EC%8A%A4%ED%82%A4_%EB%B6%84%ED%95%B4)

In [7]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
print(x)
L = np.linalg.cholesky(x)
print(L)
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


## Q6.
x의 qr인수분해를 계산하고 검증한다.<br/>
Compute the qr factorization of x and verify it.

* QR 분해(QR decomposition, QR factorization)는 행렬 분해의 일종으로 임의의 행렬을 직교행렬과 상삼각행렬의 곱으로 분해하는 방법이다. QR 분해는 선형 최소제곱법을 풀 때나 고유벡터를 구할 때 등의 상황에 사용되며, 그람-슈미트 직교정규화 혹은 하우스홀더 행렬, 기븐스 회전 등을 사용한다.
* [QR 분해 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/QR_%EB%B6%84%ED%95%B4)

In [8]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print('q=\n', q, '\nr=\n', r)

q=
 [[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]
