* 출처 : [numpy_exercises/Set_routines_Solutions.ipynb at master · Kyubyong/numpy_exercises](https://github.com/Kyubyong/numpy_exercises/blob/master/Set_routines_Solutions.ipynb)

* numpy set routine의 문제풀이 따라하기

# Set routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

In [3]:
!python --version

Python 3.6.1


##  Making proper sets
## Q1.
x에서 유일한 요소와 재구성 인덱스를 구해 x를 재구성한다.<br/>
Get unique elements and reconstruction indices from x. And reconstruct x.

In [4]:
x = np.array([1, 2, 6, 4, 2, 3, 2])
x

array([1, 2, 6, 4, 2, 3, 2])

In [5]:
out, indices = np.unique(x, return_inverse=True)
print('unique elements = ', out)
print('reconstruction indices = ', indices)
print('reconstructed = ', out[indices])

unique elements =  [1 2 3 4 6]
reconstruction indices =  [0 1 4 3 1 2 1]
reconstructed =  [1 2 6 4 2 3 2]


## 부울연산
## Q2. 
x와 같은 모양의 부울 배열을 만든다. x의 각 요소가 y에 있으면 결과는 True이고, 그렇지 않으면 False다.<br/>

Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [6]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])
# x 배열 각 요소의 값이 y 배열에 있는 값이라면 True를 아니라면 False를 출력한다.
print(np.in1d(x, y))

[ True  True False False  True]


## Q3.
x 와 y의 고유한 교차점을 찾는다.<br/>
Find the unique intersection of x and y.

In [7]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
# x, y의 공통된 요소를 찾는다.
print(np.intersect1d(x, y))

[0 1]


## Q4. 
y에 없는 x의 고유 요소를 찾는다.<br/>
Find the unique elements of x that are not present in y.

In [8]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
# setdiff1d 로 y에 없고 x에만 있는 값을 찾는다.
print(np.setdiff1d(x, y))

[2 5]


## Q5. 
x와 y의 xor요소를 찾는다.<br/>
Find the xor elements of x and y.

In [9]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
# setxor1d로 xor 요소를 찾는다.
out1 = np.setxor1d(x, y)
# setdiff1d 로 각 요소에만 있는 값을 찾은 뒤 concatenate로 합쳐준다.
out2 = np.sort(np.concatenate((np.setdiff1d(x, y), np.setdiff1d(y, x))))
assert np.allclose(out1, out2)
print(out1)

[2 4 5]


## Q6.
x와 y의 합집합을 찾는다.<br/>
Find the union of x and y.

In [10]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
# union1d 로 x, y의 합집합을 찾는다.
out1 = np.union1d(x, y)
# x, y를 합쳐주고 중복 된 요소를 unique로 걸러주고 sort한다.
out2 = np.sort(np.unique(np.concatenate((x, y))))
assert np.allclose(out1, out2)
print(out1)

[0 1 2 4 5]
