출처 : [numpy_exercises/Sorting_searching_and_counting.ipynb at master · Kyubyong/numpy_exercises](https://github.com/Kyubyong/numpy_exercises/blob/master/Sorting_searching_and_counting.ipynb)
    
# Sorting, Searching and counting 

* 연습문제 따라하기    

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

# 정렬 Sorting
## Q1.
두 번째 축을 따라 x를 정렬한다.<br/>
Sort x along the second axis.

In [3]:
x = np.array([[1, 4], [3, 1]])
out = np.sort(x, axis=1)
x.sort(axis=1)
assert np.array_equal(out, x)
print(out)

[[1 4]
 [1 3]]


## Q2. 
이름과 성의 짝을 정렬하고 색인을 리턴한다.<br/>
Sort pairs of surnames and first names and return their indices. (first by surname, then by name).


In [4]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((first_names, surnames))

array([1, 2, 0])

## Q3. 
두 번째 축을 따라 x를 정렬하는 인덱스를 가져온다.<br/>
Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1, 4, 2], [3, 1, 5]])
# 해당 위치에 정렬 순서를 기져온다.
out = np.argsort(x, axis=1)
out

array([[0, 2, 1],
       [1, 0, 2]])

## Q4. 
다섯 번째 요소가 x의 정렬 된 요소와 같고 다른 요소를 해당 값으로 나눌 수 있도록 배열을 만든다.<br/>
Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [6]:
x = np.random.permutation(10)
print('x=', x)
print("\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n",)
# 방법1
out = np.partition(x, 5)
print('out=', out)
# 방법2
x.partition(5)
print('x=', x)
# 방법1과 방법2의 결과를 비교
assert np.array_equal(x, out)
print(out)

x= [0 6 1 7 2 4 9 5 3 8]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5

out= [1 0 2 3 4 5 6 7 8 9]
x= [1 0 2 3 4 5 6 7 8 9]
[1 0 2 3 4 5 6 7 8 9]


## 검색 Searching 